set(CPPFORMAT_FOUND 0)

file(GLOB_RECURSE CPPFORMAT_SOURCE_DIR_INNER ${DEPENDENCIES_DIR}/cppformat*/fmt/format.h)

GET_FILENAME_COMPONENT(CPPFORMAT_SOURCE_DIR ${CPPFORMAT_SOURCE_DIR_INNER} DIRECTORY)
GET_FILENAME_COMPONENT(CPPFORMAT_SOURCE_DIR ${CPPFORMAT_SOURCE_DIR} DIRECTORY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPPFORMAT DEFAULT_MSG CPPFORMAT_SOURCE_DIR)


mark_as_advanced(
  CPPFORMAT_SOURCE_DIR
)
