set(GTEST_FOUND 0)

file(GLOB_RECURSE GTEST_INCLUDE_DIRS ${DEPENDENCIES_DIR}/gtest*/gtest.h)
LIST(GET GTEST_INCLUDE_DIRS -1 GTEST_INCLUDE_DIR_INNER)
GET_FILENAME_COMPONENT(GTEST_INCLUDE_DIR_INNER ${GTEST_INCLUDE_DIR_INNER} DIRECTORY)
GET_FILENAME_COMPONENT(GTEST_INCLUDE_DIR ${GTEST_INCLUDE_DIR_INNER} DIRECTORY CACHE)

GET_FILENAME_COMPONENT(GTEST_LIBRARY_DIR ${GTEST_INCLUDE_DIR} DIRECTORY CACHE)


include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(googletest DEFAULT_MSG GTEST_INCLUDE_DIR)

mark_as_advanced(
  GTEST_INCLUDE_DIR
)
