SET(ASMJIT_FOUND 0)

FILE(GLOB_RECURSE ASMJIT_SOURCE_DIR_INNER ${DEPENDENCIES_DIR}/asmjit*/asmjit.h)
GET_FILENAME_COMPONENT(ASMJIT_SOURCE_DIR_INNER ${ASMJIT_SOURCE_DIR_INNER} DIRECTORY)
GET_FILENAME_COMPONENT(ASMJIT_SOURCE_DIR ${ASMJIT_SOURCE_DIR_INNER} DIRECTORY CACHE)
GET_FILENAME_COMPONENT(ASMJIT_BINARY_DIR ${ASMJIT_SOURCE_DIR} DIRECTORY CACHE)
SET(ASMJIT_BINARY_DIR "${ASMJIT_BINARY_DIR}/build")


include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AsmJit DEFAULT_MSG ASMJIT_SOURCE_DIR)

mark_as_advanced(
  ASMJIT_SOURCE_DIR
  ASMJIT_BINARY_DIR
)
