set(SPDLOG_FOUND 0)

file(GLOB_RECURSE SPDLOG_INCLUDE_DIR_INNER ${DEPENDENCIES_DIR}/spdlog*/spdlog.h)
GET_FILENAME_COMPONENT(SPDLOG_INCLUDE_DIR ${SPDLOG_INCLUDE_DIR_INNER} DIRECTORY CACHE)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Spdlog DEFAULT_MSG SPDLOG_INCLUDE_DIR)

mark_as_advanced(
  SPDLOG_INCLUDE_DIR
)
